FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages  ./packages

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

COPY ./package.json ./package.json

COPY ./apps/http-backend/package.json ./apps/http-backend/package.json
COPY ./apps/http-backend/tsconfig.json ./apps/http-backend/tsconfig.json
COPY ./apps/http-backend/src ./apps/http-backend/src

RUN pnpm install
RUN pnpm db:generate

EXPOSE 3001

CMD [ "pnpm", "start:http" ]
