FROM node:20-alpine
WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json

COPY ./apps/web ./apps/web

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm install prisma
RUN pnpm db:generate
RUN DATABASE_URL=${DATABASE_URL} pnpm build

EXPOSE 3000

CMD [ "pnpm", "start:web" ]
