FROM node:20-alpine
WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json

COPY ./apps/ws-backend/package.json ./apps/ws-backend/package.json
COPY ./apps/ws-backend/tsconfig.json ./apps/ws-backend/tsconfig.json
COPY ./apps/ws-backend/src ./apps/ws-backend/src

RUN npm install -g pnpm rimraf typescript ts-node
RUN pnpm install
RUN pnpm db:generate

EXPOSE 8080

CMD [ "pnpm", "start:ws" ]
